condense_wildcard_suffixes = true
fn_single_line = false
format_strings = true
match_block_trailing_comma = true
normalize_comments = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
